theme: jekyll-theme-slate

# Setup
title:            Sijia's Blog
tagline:          'Towards Data Scientist'
description:      'Everyday learn something new!'
baseurl:          https://sijiali57.github.io/home
url:              https://sijiali57.github.io/home

author:
  name:           'Sijia Li'
  url:            https://github.com/sijiali57
  # email:          xxx
  # home:           https://

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Page Settings
sidebar_home_link:  true
paginate:         10

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll-postfiles
